title: "MedCom HospitalNotification Profiles in FHIR"
description: "This page includes content about MedCom HospitalNotification profiles"
logo: medcom+fhir-logo.png
description: "MedCom standard based on HL7 FHIR"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
version: "Version 1.0.0-alpha.1"
fhir_version: "FHIR R4"